version: '3.1'
services:
  front:
    build:
      context: src/
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 127.0.0.1:${FRONT_PORT:-3009}:3000
    volumes:
      - ./src:/src
      - /src/node_modules
      - /src/.next
